# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/94ed4718-bead-49d2-b18e-d7ed691d3c66";
  boot.initrd.luks.devices."crypthome".device = "/dev/disk/by-uuid/5c3a1bc8-b51f-4cac-9088-5acec2a60c70";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1FD5-453E";
      fsType = "vfat";
      options = [ "noauto" "x-systemd.automount" ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3aaa975b-55af-476c-adce-431d8af5accc";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e6468e11-de80-4269-b728-d4ddb4366e9e";
      fsType = "ext4";
      options = [ "noauto" "x-systemd.automount" ];
  };

  fileSystems."/mnt/hactar" =
    { device = "10.3.0.2:/media/files";
      fsType = "nfs4";
      options = [ "ro" "noauto" "x-systemd.automount" ];
  };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = "powersave";
}
